name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test basic example
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        python -c '
        import mlx.core as mx
        from bandit_sim import BanditEnvironment, ThompsonSampling, run_simulation
        
        env = BanditEnvironment(
            true_rewards=mx.array([0.1, 0.5, 0.3, 0.7, 0.2]),
            seed=42
        )
        
        algorithm = ThompsonSampling(num_arms=5, alpha=1.0, beta=1.0, seed=42)
        metrics = run_simulation(env, algorithm, num_steps=100)
        
        print(f"Total reward: {float(metrics[\"cumulative_reward\"][-1]):.2f}")
        print(f"Total regret: {float(metrics[\"cumulative_regret\"][-1]):.2f}")
        print("Basic example test passed!")
        '
    
    - name: Run demo script
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        python demo.py
    
    - name: Set artifact name
      id: artifact
      run: |
        VERSION="${{ matrix.python-version }}"
        SAFE_VERSION="${VERSION//./}"
        echo "name=demo-outputs-python-${SAFE_VERSION}" >> $GITHUB_OUTPUT
    
    - name: Upload demo outputs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: |
          easy_scenario.png
          hard_scenario.png
        retention-days: 7
